### ISSUE TITLE
Продолжаю получить ошибки

### ISSUE THREAD

**Issue by YoyoKarimov** [hcodes/server_yametrika_nodejs#6]
{ Error: connect ETIMEDOUT 87.250.250.119:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '87.250.250.119',
  port: 443 }
{ Error: connect ETIMEDOUT 77.88.21.119:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '77.88.21.119',
  port: 443 }

**Comment by hcodes** [comment]
IP-адрес Яндекса, соединение отвалилось по таймауту.

**Comment by YoyoKarimov** [comment]
Я понимаю что ip яндекса.
Не понимаю как ловить такие ошибки.

**Comment by YoyoKarimov** [comment]
В общем то добавление которое сделали в новой версии не решило проблемы.
Как было так и остались ошибки.
Есть варианты решения?

**Comment by hcodes** [comment]
Пока не смотрел.

**Comment by YoyoKarimov** [comment]
Еще раз здравствуйте!
Есть какие нибудь продвижки по решению проблемы с ECONNRESET?

**Comment by hcodes** [comment]
Могу сделать проброс `agent` в https-запросе с `keepAlive: true`. Должно помочь.

https://stackoverflow.com/questions/24320578/node-js-get-request-etimedout-esockettimedout/43857814#43857814

**Comment by YoyoKarimov** [comment]
Давайте попробуем.
Я, к сожалению, не знаю как решить проблему.
По теме ECONNRESET в nodejs куча разных статей, но нигде нет конкретных шагов.

Буду ждать обновленную версию.

**Comment by hcodes** [comment]
```js
const https = require('https');
const agent = new https.Agent({ keepAlive: true });
const counter = require('yametrika').counter({ id: '...', agent: agent });
```

Отпишитесь, пожалуйста, помогло это или нет.

**Comment by hcodes** [comment]
Выпустил версию с пробросом agent [v2.2.0](https://github.com/hcodes/server_yametrika_nodejs/releases/tag/v2.2.0).

**Comment by YoyoKarimov** [comment]
Протестировал.
К сожалению не помогло:
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

**Comment by YoyoKarimov** [comment]
Есть мысли как поправить?
У меня вот после обновления стали появляться еще вот такие вот ошибки

{ Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
    at Object.onceWrapper (events.js:277:13)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: null,
  host: 'mc.yandex.ru',
  port: 443,
  localAddress: undefined }

**Comment by hcodes** [comment]
Я могу сделать приватный метод, который будет только отправлять данные в Метрику. Его можно будет перезаписать и добавить нужные параметры или свои обработчики.
https://github.com/hcodes/server_yametrika_nodejs/blob/master/yametrika.js#L275

**Comment by YoyoKarimov** [comment]
Т.е. вынести функцию в основной скоп и там уже пытаться отлавливать его ошибки ?

Как вариант можно попробовать, но тут не ясно в каком именно месте падает с ошибкой.

**Comment by YoyoKarimov** [comment]
Добрый день!
Есть какие нибудь подвижки в данном направление?
